services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${BACKEND_PORT}/health-check"
        ]
      interval: 1s
      timeout: 10s
      retries: 10
  frontend:
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:${FRONTEND_PORT}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
