services:
  postgres:
    extends:
      file: base.yml
      service: postgres
    restart: always
  backend:
    extends:
      file: base.yml
      service: backend
    build:
      context: ./backend
      target: test
    command: >
      sh -c "/app/backend/bin/create_db.sh &&
             /app/backend/bin/migrate.sh &&
             /app/backend/bin/start.sh"
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    extends:
      file: base.yml
      service: frontend
    build:
      context: ./frontend
      target: test
    command: >
      bash -c "/app/frontend/bin/start.sh"
    depends_on:
      backend:
        condition: service_healthy
